### ISSUE TITLE
Remove ./pf go module

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1445]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Consider removing pf/go.mod Go module and folding it into the top-level ./go.mod module. This is a breaking change for consumers that will need to adjust their Go references. 

The benefit of doing this is simply managing providers:

- pf and . are already released on the same cadence in practice,  this makes it more obvious
- eliminate a class of issues with accidentally misaligned versions of . and ./pf that do not compile or do not work together
- simplify tooling for releases and upgrades

The downside is that dependencies from `./pf` including Plugin Framework dependencies will be added to all bridged providers even if they are not using Plugin Framework internally. This may be an acceptable cost to pay.

**Comment by blampe** [comment]
> The downside is that dependencies from ./pf including Plugin Framework dependencies will be added to all bridged providers even if they are not using Plugin Framework internally. This may be an acceptable cost to pay.

Go will only use the dependencies it needs, so there is no cost to doing this. I suspect this line of thinking arose due to the way pu/pu exports a large chunk of the AWS SDK as part of its integration helpers, so consuming it tends to blow up indirect dependencies. But again this doesn't matter if a project doesn't actually consume the AWS SDK.

It's easy enough to confirm this locally by standing up a project that imports the `pf` module directly, and then use a `replace` to point it at a local copy without the module. The only thing that changes is you no longer have a `go.sum` reference to the deleted module.

```
❯ diff -u go.mod-before go.mod
--- go.mod-before	2024-08-21 13:16:10
+++ go.mod	2024-08-21 13:21:46
@@ -2,8 +2,10 @@

 go 1.22.6

-require github.com/pulumi/pulumi-terraform-bridge/pf v0.42.1
+require github.com/pulumi/pulumi-terraform-bridge v0.0.0-00010101000000-000000000000

+replace github.com/pulumi/pulumi-terraform-bridge => /Users/bryce/src/pulumi-terraform-bridge
+
 require (
 	github.com/hashicorp/terraform-plugin-go v0.22.0 // indirect
 	github.com/pulumi/pulumi-terraform-bridge/v3 v3.89.1 // indirect


❯ diff -u go.sum-before go.sum
--- go.sum-before	2024-08-21 13:16:15
+++ go.sum	2024-08-21 13:21:47
@@ -6,8 +6,6 @@
 github.com/hashicorp/terraform-plugin-go v0.22.0/go.mod h1:mPULV91VKss7sik6KFEcEu7HuTogMLLO/EvWCuFkRVE=
 github.com/pmezard/go-difflib v1.0.0 h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=
 github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
-github.com/pulumi/pulumi-terraform-bridge/pf v0.42.1 h1:IMn3MmvoO66iptcU5kBdun60PqwNJBJ20A4hD3AqkDE=
-github.com/pulumi/pulumi-terraform-bridge/pf v0.42.1/go.mod h1:SXxx1PJNNdGoD4/CxELgy0F46uzcTbDkz63DJsjIRXE=
 github.com/pulumi/pulumi-terraform-bridge/v3 v3.89.1 h1:FLQknb6r3r/uaj1XLbouFF88eF1Fk0h4JOVS9kHKDRY=
 github.com/pulumi/pulumi-terraform-bridge/v3 v3.89.1/go.mod h1:JAxygKR/XGW6zIv6iOP6sHAYjZ7OCtqU7j6Od1lUk38=
 github.com/stretchr/testify v1.9.0 h1:HtqpIVDClZ4nwg75+f6Lvsy/wHu+3BoSGCbBAcpTsTg=
```

The answer to "Should this be a module?" is almost always a resounding ["No!"](https://go.dev/wiki/Modules#should-i-have-multiple-modules-in-a-single-repository)

Other instances where unnecessary `go.mod` files have made life harder than necessary for us:
* https://github.com/pulumi/pulumi-service/pull/20778
* https://github.com/pulumi/pulumi-go-provider/pull/231

**Comment by t0yv0** [comment]
I'd very much like to do this but might need help, it is easy conceptually but there's some lift refactoring tests.

**Comment by VenelinMartinov** [comment]
I had a go at this: https://github.com/pulumi/pulumi-terraform-bridge/pull/2358 but lost steam, it's quite some refactoring

**Comment by blampe** [comment]
> I had a go at this: [#2358](https://github.com/pulumi/pulumi-terraform-bridge/pull/2358) but lost steam with the tests, it's quite some refactoring. Would be happy to help if we pick it up again.

@VenelinMartinov I'd suggest scoping this down to _only_ removing modules and otherwise leaving the existing code as-is. Ensuring that still builds and behaves as expected is enough work on its own. I took a swing at that here https://github.com/pulumi/pulumi-terraform-bridge/pull/2473

Then in a followup you can start consolidating, deprecating things, etc.
