### ISSUE TITLE
TF schema generator ignores type difference inputs vs outputs

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-terraform-bridge#152]
I may be confused about how things are intended to work, so I'm opening this issue to get a confirmation that it's an actual problem.

I'll illustrate with an example. The current Azure schema contains this snippet:

```
"azure:storage/account:Account": {
    "description": "Manages an Azure Storage Account.\n\n{{% examples %}}\n{{% /examples %}}\n",
    "properties": {
        ...
        "identity": {
            "$ref": "#/types/azure:storage/AccountIdentity:AccountIdentity",
            "description": "A `identity` block as defined below.\n"
        },
        ...
    "inputProperties": {
        ...
        "identity": {
            "$ref": "#/types/azure:storage/AccountIdentity:AccountIdentity",
            "description": "A `identity` block as defined below.\n"
        },
```

As I read it, it points to the same type both from an input property `identity` and from the corresponding output property `identity`.

The problem is that those types should be different. The current (non-schema-based) Azure code in C# has a separate args (inputs) type -- note a nullable `PrincipalId`:

```csharp
public sealed class AccountIdentityArgs : Pulumi.ResourceArgs
{
    [Input("principalId")]
    public Input<string>? PrincipalId { get; set; }
```

https://github.com/pulumi/pulumi-azure/blob/ffeb2d2020298598f12fd7705bde6cf7ccf3cd36/sdk/dotnet/Storage/Account.cs#L1005-L1011

and a separeate output type (not a non-nullable `PrincipalId`):

```csharp
[OutputType]
public sealed class AccountIdentity
{
    public readonly string PrincipalId;
```

https://github.com/pulumi/pulumi-azure/blob/ffeb2d2020298598f12fd7705bde6cf7ccf3cd36/sdk/dotnet/Storage/Account.cs#L1694-L1699

I suspect that the schema generator loses information about required properties, which leads to the diff in generated non-schema vs. schema-based Azure C# code:

```diff
 [Pulumi.OutputType]
    public sealed class AccountIdentity
    {
-       public readonly string PrincipalId;
-       public readonly string TenantId;
+       public readonly string? PrincipalId;
+       public readonly string? TenantId;
        public readonly string Type;
    }
```

https://github.com/mikhailshilkov/api-compare/pull/1/files#diff-2eb546cb2cda8f85dd3888495e6511b4L47886

@pgavlin Does this make sense?

**Comment by lukehoban** [comment]
I believe this is because the upstream provider has this:

```
                                        "principal_id": {
							Type:     schema.TypeString,
							Computed: true,
                            		},

```

We previously interpreted `Computed: true` as a non-nullable output property. I believe now we interpret that as being a potentially null output, unless `Required: true` is also provided. There are three issues with that:
1. I’m not actually sure that’s the “correct” interpretation of the TF schema (though I can’t find any clear documentation either way)
2. In practice, it certainly isn’t adhered to well by actual providers - most output properties are guaranteed always to be set to non-null values in practice (by inspecting implementation), but very very few mark computers as Required. 
3. This change from a Pulumi perspective is a significance breaking change for all languages, and we will almost certainly have to undo it at least for TypeScript - but if so probably should be consistent and undo it for all languages (i.e. at the schema level). 

Definitely interested in @pgavlin’s thoughts as well.

**Comment by leezen** [comment]
We discussed this and decided this behavior is "by design" for now. We can have a broader discussion around potentially changing this behavior (which would impact all schema-based codegen).
