### ISSUE TITLE
Some TFPF nested resources do not map correctly

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#1657]
### What happened?

During testing for https://github.com/pulumi/pulumi-terraform-bridge/pull/1650, it was revealed that a few nested fields in pulumi-aws resources bridged via Terraform Plugin Framework were getting bridged to `schemashim.typeSchema` instead of `schemashim.attrSchema`.

This caused a panic on `make tfgen` since `schemashim.TypeSchema` [does not currently implement a `Description()` method.](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pf/internal/schemashim/type_schema.go#L102)

### Example

Run the bridge version in https://github.com/pulumi/pulumi-terraform-bridge/pull/1650 against pulumi-aws, but re-implement the panic on Description().

[Here's an AWS branch](https://github.com/pulumi/pulumi-aws/tree/guin/unicorn-debug-tfpf) that replaces the Description() return value with `WHAT IS THIS UNICORN SPECIAL JAMSAUCE - I am a TFPF Type resource` - there are only about 6 affected fields. 

### Output of `pulumi about`

n/a

### Additional context

Here's the upstream code for one of the resources that's not being mapped to `schemashim.attrSchema`:
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/lexv2models/bot_version.go#L79

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
I'm a little confused on the impact here. Why is `schemashim.typeSchema` wrong? How does this effect users?

Is this an internal representation issue that causes #1650 to panic when tested on pulumi-aws?

**Comment by t0yv0** [comment]
```
// MapAttribute represents a schema attribute that is a list with a single
// element type. When retrieving the value for this attribute, use types.Map
// as the value type unless the CustomType field is set. The ElementType field
// must be set.
//
// Use MapNestedAttribute if the underlying elements should be objects and
// require definition beyond type information.
//
// Terraform configurations configure this attribute using expressions that
// return a list or directly via curly brace syntax.
//
//	# map of strings
//	example_attribute = {
//		key1 = "first",
//		key2 = "second",
//	}
//
// Terraform configurations reference this attribute using expressions that
// accept a map or an element directly via square brace string syntax:
//
//	# key1 known element
//	.example_attribute["key1"]
type MapAttribute struct {

```

The problem is that when nesting objects the comments recommend MapNestedAttribute but that's not what AWS uses. Indeed it uses MapAttribute. It thought this is disallowed but it's discouraged but allowed. Since they opted to do this, PF doesn't consider the underlying object's fields attributes anymore and we get typeSchema. That is not wrong but a reasonable behavior. 

What I am worried about though still is that map of objects used to be unrepresentable in TF SDK v2, and consequently it was unrepresentable in shim.Provider; like you could only do SingleNestedBlock which would translate to a TypeMap with a Resource inside, but the meaning of that was not `Map<string, {x: float, y:float}>` but `{x: float, y:float}` the TypeMap being a misnomer. 

This resource as far as I can tell from examples on TF website is a bona fide map-of-objects. So I need to double-check if this projects correctly to say TypeSCript and indeed works at runtime.

**Comment by t0yv0** [comment]
Huh, never mind, this seems to work fine. Looks like attributes map-of-objects parse fine and the limitation is only on blocks. Fascinating. Well with this information, I don't think there's any remaining problem here.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const test = new aws.lex.V2modelsBotVersion("test", {
    botId: "botid",
    localeSpecification: {
        en_US: {
            sourceBotVersion: "DRAFT",
        },
    },
});

```

**Comment by t0yv0** [comment]
schemashim.typeSchema may return "" then (no description) and expect to be called in tfgen.
