### ISSUE TITLE
Review Docs tracking issues for additional low effort fixes

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-terraform-bridge#1795]
We have 3 issues tracking patterns of documentation bugs:
[[Tracking Issue] Incorrect API Docs· pulumi-terraform-bridge/1292](https://github.com/pulumi/pulumi-terraform-bridge/issues/1292)
[[Tracking Issue] Misformatted API Docs· pulumi-terraform-bridge/1291](https://github.com/pulumi/pulumi-terraform-bridge/issues/1291)
[[Tracking Issue] Missing Generated Documentation· pulumi-terraform-bridge/1290](https://github.com/pulumi/pulumi-terraform-bridge/issues/1290)

We should review this list and cut tickets for the work we think would be needed to fix them. Low-effort fixes (<=1 day) can be added to the https://github.com/pulumi/pulumi-terraform-bridge/issues/1794 effort; more involved problems will be tracked for future docs investment.

**Comment by guineveresaenger** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/807 - this will take a little bit of digging in why the import logic isn't picking up the correct package name.

https://github.com/pulumi/pulumi-signalfx/issues/377 came out of left field via upstream upgrade. Needs investigation.

https://github.com/pulumi/pulumi-aws/issues/2427 is a common bug where not all Descriptions are properly re-edited to reflect pulumi names. There's probably more than one occurrence of this. May be worth looking into - but will likely take more than one day, as there are likely multiple sources of this bug.

https://github.com/pulumi/pulumi-terraform-bridge/issues/351 - we may need some design on this since we do not know how often this behavior occurs throughout the docs, and what we would like to see instead. Current practices show that we actually just remove a lot of these inline links [via replacements.json](https://github.com/pulumi/pulumi-aws/pull/2886). The example given in the issue does not follow a simple rule and may need a one-off fix, but that doesn't address the entire issue.

I've moved all other issues to #1794.

**Comment by guineveresaenger** [comment]
I've gone through all the linked tracking issues, commented on open issues and made a call on whther it's a straightforward or more involved fix.

Added the quick issues to #1794 and remarked the remainder in here. Do we want to open a new tracking issue for the longer-term investments? if yes, I can do that and close out this issue as well.
