### ISSUE TITLE
Encountering Panic: `inconsistent list element types`

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-terraform-bridge#1932]
### What happened?

When using the pulumi-terraform-bridge I am encountering a panic 

`panic: inconsistent list element types (cty.Object(map[string]cty.Type{"resource_type":cty.String, "tags":cty.String}) then cty.Object(map[string]cty.Type{"resource_type":cty.String, "tags":cty.Map(cty.String)}))`

I will attach the full stack trace separately.

### Example

n/a

### Output of `pulumi about`

pulumi-terraform-bridge 3.80.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by zbuchheit** [comment]
Repro: 

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/ec2"
	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		bucket, err := s3.NewBucket(ctx, "my-bucket", nil)
		if err != nil {
			return err
		}

		template, err := ec2.NewLaunchTemplate(ctx, "zbuchheit-launch-template", &ec2.LaunchTemplateArgs{
			ImageId: pulumi.String("dummyImageIdBecauseItIsAPreview"),
			TagSpecifications: &ec2.LaunchTemplateTagSpecificationArray{
				&ec2.LaunchTemplateTagSpecificationArgs{
					ResourceType: pulumi.String("resourceType1"),
					Tags: pulumi.StringMap{
						"Name": bucket.Arn.ApplyT(func(v string) string {
							return fmt.Sprintf("Bucket Arn %s", v)
						}).(pulumi.StringOutput),
					},
				},
				&ec2.LaunchTemplateTagSpecificationArgs{
					ResourceType: pulumi.String("resourceType2"),
					Tags: pulumi.StringMap{
						"Name": pulumi.String("Bucket Arn"), // If you make this an output also, the panic will go away
					},
				},
			},
		},
		)
		if err != nil {
			return err
		}

		ctx.Export("bucket", bucket)
		ctx.Export("template", template)
		return nil
	})
}
```

**Comment by corymhall** [comment]
Looks like this is due to us rolling out `PlanResourceChange` to the launch template resource in https://github.com/pulumi/pulumi-aws/pull/3687.

1. We will go ahead and revert that PR since the bug that was fixing was a diff bug which is less critical than this p1.
2. We need to rewrite the [objectFromCtyValue](https://github.com/pulumi/pulumi-terraform-bridge/blob/935ad83006358781cdd9b66b85a872e296c6c0d5/pkg/tfshim/sdk-v2/instance_state.go#L69-L86) function. We will need to implement our own transform function to handle converting the `cty` value to a JSON map.

**Comment by t0yv0** [comment]
CC @VenelinMartinov @iwahbe - we might have a fix here FYI.
