### ISSUE TITLE
PF update proposed new to pull recent upstream changes

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2172]
### What happened?

We have an adaptation of upstream's objchange in PF: https://github.com/opentofu/opentofu/tree/main/internal/plans/objchange

https://github.com/pulumi/pulumi-terraform-bridge/blob/18db7c57211af0eb7dfa26a70b145edc4d33a88f/pf/internal/pfutils/proposed_new.go#L26-L27

This hasn't been updated in a while but upstream has had a few changes - we might need to update our copy too.

This is a bit more involved than it is in the SDKV2 bridge - there we have a direct copy of the code which we use as is - in PF it is re-implemented as it works with the tftypes instead of the cty values.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
So I think this is interesting, we should be using vendored objchange.ProposedNew instead of the homegrown version to minimize discrepancies. Looks like one attempt was made https://github.com/pulumi/pulumi-terraform-bridge/pull/1276 but rejected for expediency as it had some concerns. Still I think that might be the way, we might need to add test cases to push through concerns but ultimately use the implementation from opentofu.

**Comment by t0yv0** [comment]
I've started working toward this and will try to complete in M107. Thanks!
