### ISSUE TITLE
Support Alternative Documentation Paths

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#240]
There are 2 problems that need addressed here:

1. Modules that do not follow the standard TF module structure and store docs in a location other `website/docs/{r,d}/resource.md`. 
	This alternative download path may require us to scrape the docs directly from GitHub rather than using the GOPATH locally

2. There are situations where a provider is moving from org X to org Y and the go.mod still shows the module name referencing org X. 
This leads us to not be able to load documentation for that specific module.

**Comment by komalali** [comment]
I'm going to put this back in the input queue for now because it's not the actual culprit for the bug we're seeing in pulumi-random, but I did spend a little bit of time looking into this so adding that information here.

We already have a [solution](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/docs.go#L128-L137) for (1) where we look at different possibilities for the file name. If there are examples where this isn't working, we can look into improving this logic.

I don't believe (2) is an actual problem. It doesn't matter if the repo has changed orgs, the module files will always follow the module name that is specified in go.mod.
