### ISSUE TITLE
Test Terraform integration

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform-bridge#34]
At the moment, we don't really test the Terraform integration specifically.  It's a little tricky to do this because we need a kind of null Terraform provider with enough "interesting cases".  To do this probably means creating our own test provider and then driving it through the generated code.

**Comment by t0yv0** [comment]
Since this issue was written we're doing a few more kinds of testing of this sort. There's more testproviders: 

https://github.com/pulumi/pulumi-terraform-bridge/tree/master/internal/testprovider

In the case of Plugin Framework there's a few more:

https://github.com/pulumi/pulumi-terraform-bridge/tree/master/pf/tests/internal/testprovider
