### ISSUE TITLE
Add Grafana Cloud provider

### ISSUE THREAD

**Issue by kiweezi** [pulumi/pulumi-terraform-bridge#596]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We would like to be able to control our Grafana cloud platform with Pulumi.
Currently, this is not available in Pulumi, however I can see that Terraform has a provider.

### Affected area/feature

Terraform Bridge / Registry

**Comment by kiweezi** [comment]
Looks like this was [tried in the past](https://github.com/igordrnobrega/pulumi-grafana), though it looks like it's not being worked on anymore.
I'm not sure what the cause was to stop developing this.

**Comment by stack72** [comment]
Hi @kiweezi 

I have included a link to a document that can help you bridge this provider if you want :) This is not something in our immediate plans

Paul

**Comment by kiweezi** [comment]
> Hi @kiweezi
> 
> I have included a link to a document that can help you bridge this provider if you want :) This is not something in our immediate plans
> 
> Paul

Hey @stack72, thanks for the response!
I'm not sure I can find the link you are suggesting.

Also, would you be able to provide an explanation about why this provider will not be added? It might help us head in the right direction.

**Comment by stack72** [comment]
Hi @kiweezi 

My apologies for not adding the link itself - https://github.com/pulumi/pulumi-tf-provider-boilerplate#creating-a-pulumi-terraform-bridge-provider

We (as a team) are not able to accomodate every ISV tool in the ecosystem. It has an overhead to build and maintain these providers that would stop the team being able to build the systems required to make the providers better. We are happy to support our community in building and publishing the providers to allow their good work to be recognised by others

I am more than happy to get on a call and help you bridge the provider so that you would be able to use it

Paul

**Comment by kiweezi** [comment]
Hey Paul @stack72,

Thanks for the link!
That's understandable, you guys already have enough to work on!

That's very generous of you to offer your help! I must admit, I'm interested, but I'm not sure I'm the right person for the job. I've never used golang or typescript... I wouldn't know how to setup e2e tests.
I would love to give it a go though, how much work do you think it is? Is most of the work in maintaining things?
