### ISSUE TITLE
Bridge versions 3.39.x occasionally missing examples during generation

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-terraform-bridge#801]
Reproduced in azure-classic in this PR: https://github.com/pulumi/pulumi-azure/pull/1205

- Downgrading to 3.38.1 resolves the issue.
- Using both 3.39.0 and 3.39.3 introduces unreliable generation.

Having performed a clean build locally, CI will fail with dirty working tree due to generation behaviour being inconsistent.

**Comment by t0yv0** [comment]
Daniel reproduced with 3.38.1

**Comment by t0yv0** [comment]
This appears to be a bug in pulumi/pulumi#12130 that sporadically corrupts schema cache by confusing azuread and azure. The azure codebase requests azuread schema to be loaded to render examples. When this corruption happens the rendering fails, the bridge swallows panics and examples. To trigger this, the versions of azuread and azure need to align it seems, which is rare. Note also when reproducing, you must make sure the local binary is versioned exactly v5.33.0. This explains CI non-determinism since his worked before the release was tagged and stopped working after it was tagged, on same commits.

```bash
$ jq .name ~/.pulumi/plugins/schema-azuread-5.33.0-.json 
"azure"
```

Repro:

```
git tag v5.33.0 --force
pulumi plugin rm --all --yes
rm -rf ~/.pulumi/plugins
git clean -fxd
make tfgen
```

**Comment by t0yv0** [comment]
Apologies looks like it's in the tfbridge code after all. Here it is https://github.com/pulumi/pulumi-terraform-bridge/pull/805
